services:
  bot:
    build: .
    container_name: maxwed-bot
    user: "1001:1001"
    restart: always
    env_file:
      - .env
    volumes:
      - ./key.bin:/app/key.bin:ro
      - ./token.enc:/app/token.enc:ro
